export const robots = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Lgraham",
    email: "lgraham@april.biz",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Ehowell",
    email: "ehowell@melissa.tv",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "cbauch",
    email: "cbauch@yesenia.net",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "plebsack",
    email: "Julianne.OConner@kory.org",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
  },
  {
    id: 11,
    name: "Else Yost",
    username: "eyost45",
    email: "Evie_Barrows86@gmail.com",
  },
  {
    id: 12,
    name: "Fabian Bashirian",
    username: "Aniyah55",
    email: "Titus_Thompson84@email.com",
  },
  {
    id: 13,
    name: "Hardley Leannon",
    username: "Susanna.Hegmann39",
    email: "har_lean96@email.com",
  },
  {
    id: 14,
    name: "Eribito Oberbrunner",
    username: "er_ober",
    email: "er_ober_me@email.co.uk",
  },
  {
    id: 15,
    name: "Muriel Kertzmann",
    username: "Mukertz",
    email: "mkertzmann@email.io",
  },
  {
    id: 16,
    name: "Jennifer OConner",
    username: "joconner",
    email: "jkeanoski@email.ca",
  },
];
